function printHelp() {
    console.log(`Usage: puerts-uehper <command> [target] [...args] [--force] [--dry-run]

Run from the Unreal project root or any directory below it. The CLI walks upward to find the .uproject.

Package execution:
    puerts-uehper <command>
    npx puerts-uehper <command>
    npx puerts_uehper <command>

Cross-directory automation:
    puerts-uehper <command> --project <uproject-root>

Local source checkout fallback:
    node uehper.js <command> [target] [...args]

Commands:
  install    Run bootstrap, then build if Puerts typings already exist.
  doctor     Validate project layout and print the missing prerequisites.
  bootstrap  Initialize project files, dependencies, and framework links.
    gen-typings Generate Typing/ue declarations through UEHper automated Puerts.Gen.
    init       Bootstrap project files and create the minimal project app scaffold.
    make       Create app/module/ui/resource/scene/service files.
        manifest   Add resource/scene/widget entries to the configured app Manifests directory.
    ensure-cook-smoke-map  Create the dedicated /Game CookSmoke map if missing.
    ensure-ui-validation-widget  Create the project UI validation Widget Blueprint and manifest entries.
  smoke      Validate the minimal framework and project scaffold.
  build      Compile TypeScript using generated Puerts typings.
    watch      Watch project business TypeScript and emit JS into Content/JavaScript.
    sync-runtime  Sync puerts_uehper runtime into Content/JavaScript/node_modules.
  help       Show this message.

Make examples:
    puerts-uehper make app
    puerts-uehper make module ExhibitFlow
    puerts-uehper make ui GameHUD /Game/UI/WBP_GameHUD.WBP_GameHUD_C
    puerts-uehper make resource CandyMesh StaticMesh /Game/Models/Candy/SM_Candy.SM_Candy
    puerts-uehper make scene Game /Game/Levels/LEVELgame
    puerts-uehper make service ScoreService

Manifest examples:
    puerts-uehper manifest resource CandyMesh StaticMesh /Game/Models/Candy/SM_Candy.SM_Candy
    puerts-uehper manifest scene Game /Game/Levels/LEVELgame
    puerts-uehper manifest widget GameHUD /Game/UI/WBP_GameHUD.WBP_GameHUD_C --layer=HUD
    puerts-uehper manifest selected Intermediate/UEHper/SelectedAssets/selected-assets.json

Editor workflow:
    Content Browser > UEHper > Generate UEHper Manifest from Selection
    Content Browser > UEHper > Generate UEHper Manifest from Folder

Editor automation fallback:
    UEHper.ExportSelectedAssets [OutputPath]
    UnrealEditor.exe <uproject> -UEHperExportSelectedAssets=<OutputPath> -NullRHI -Unattended -NoSplash -log
    UEHper.EnsureCookSmokeMap [/Game/UEHper/CookSmoke]
    UnrealEditor.exe <uproject> -UEHperEnsureCookSmokeMap=/Game/UEHper/CookSmoke -NullRHI -Unattended -NoSplash -log
    UEHper.EnsureUIValidationWidget [/Game/UEHper/UI/WBP_UIValidation]
    UnrealEditor.exe <uproject> -UEHperEnsureUIValidationWidget=/Game/UEHper/UI/WBP_UIValidation -NullRHI -Unattended -NoSplash -log

Options:
    --force    Reinstall or resync generated files and npm dependencies.
    --dry-run  Print file operations without writing files.
    --layer    UI layer for make ui or manifest widget. Default: HUD.
    --resource-key  Resource key generated by manifest widget. Default: <UIKey>Class.
    --editor   Override UnrealEditor.exe path for gen-typings.
    --mode     Puerts.Gen mode. Default: FULL.
    --timeout-ms  Timeout for gen-typings. Default: 600000.
    --keep-editor  Keep the editor open after gen-typings.
    --asset-registry  With doctor, start UnrealEditor and validate manifest assets through UE AssetRegistry.
    --asset-registry-timeout-ms  Timeout for doctor --asset-registry. Default: 300000.
    --cook  With doctor, run UnrealEditor-Cmd Cook commandlet for a fast map Cook validation.
    --cook-platform  Target platform for doctor --cook. Default: Windows.
    --cook-map  Map package path for doctor --cook. Default: GameDefaultMap.
    --cook-smoke  With doctor --cook, use a minimal project smoke map. Default smoke map: /Game/UEHper/CookSmoke.
    --cook-smoke-map  Smoke map package path for doctor --cook --cook-smoke.
    --ensure-cook-smoke-timeout-ms  Timeout for ensure-cook-smoke-map. Default: 300000.
    --ui-validation-widget  Widget package path for ensure-ui-validation-widget. Default: /Game/UEHper/UI/WBP_UIValidation.
    --ensure-ui-validation-timeout-ms  Timeout for ensure-ui-validation-widget. Default: 300000.
    --cook-timeout-ms  Timeout for doctor --cook. Default: 1200000.
    --editor-cmd  Override UnrealEditor-Cmd.exe path for doctor --cook.
    --watch-runtime-state  With doctor, tail Saved/Logs/*.log and stream 'RuntimeState X -> Y' lines (Ctrl+C to stop).
    --watch-runtime-state-poll-ms  Poll interval for --watch-runtime-state. Default: 1000, min: 250.
    --watch-runtime-state-json  With --watch-runtime-state, emit NDJSON ({ts,log,from,to,line}) instead of text.
    --no-sync-runtime  With watch, skip the one-time runtime package sync before starting tsc --watch.
    --project  Target Unreal project root or any directory below it. Optional; default is current working directory.
    --source-root  Project TS source root. Default: TypeScript.
    --app-dir  Project app directory under --source-root. Default: Game; use . for source root.
    --entry-module  UEHper EntryModule to write during init. Default: <app-dir>/GameApp.
    --runtime-source  Runtime source for sync-runtime: auto, compiled, or dist. Default: auto.
    --framework-source  Framework TS compile source: package or source. Default: package.

Install location:
    Default npm mode materializes puerts_uehper into node_modules/puerts_uehper and maps TS imports to dist.
    Use --framework-source=source only for legacy projects that keep <source-root>/puerts_uehper.`);
}

module.exports = {
    printHelp,
};
